#!/bin/sh
set -eu

MODE="${BITCOIN_NETWORK_MODE:-dummy}"
BOOTSTRAP_HEIGHT=19
MINING_ADDRESS=mipcBbFg9gMiCh81Kj8tqqdgoZub1ZJRfn

case "$MODE" in
    dummy)
        # Preserve the original package's datadir across upgrades.
        DATA_DIR=/data
        CHAIN_OPTION=regtest
        NETWORK_SECTION=regtest
        PEER_CONFIG='dnsseed=0
fixedseeds=0'
        MODE_CONFIG='testactivationheight=blake2b@20'
        DEFAULT_HEADLINE=BIP110-LAB
        BOOTSTRAP_DUMMY=1
        ;;
    testnet4)
        DATA_DIR=/data/networks/testnet4
        CHAIN_OPTION=testnet4
        NETWORK_SECTION=testnet4
        PEER_CONFIG='dnsseed=1
fixedseeds=1
prune=550'
        MODE_CONFIG=''
        DEFAULT_HEADLINE=Totoro
        BOOTSTRAP_DUMMY=0
        ;;
    signet)
        DATA_DIR=/data/networks/signet
        CHAIN_OPTION=signet
        NETWORK_SECTION=signet
        PEER_CONFIG='dnsseed=1
fixedseeds=1
prune=550'
        MODE_CONFIG=''
        DEFAULT_HEADLINE=Totoro
        BOOTSTRAP_DUMMY=0
        ;;
    regtest)
        DATA_DIR=/data/networks/regtest
        CHAIN_OPTION=regtest
        NETWORK_SECTION=regtest
        PEER_CONFIG='dnsseed=0
fixedseeds=0'
        MODE_CONFIG=''
        DEFAULT_HEADLINE=Totoro
        BOOTSTRAP_DUMMY=0
        ;;
    *)
        echo "unsupported Bitcoin network mode: $MODE" >&2
        exit 64
        ;;
esac

HEADLINE="${BITCOIN_BLAKE2B_HEADLINE:-$DEFAULT_HEADLINE}"

mkdir -p "$DATA_DIR"
umask 077

cat > "$DATA_DIR/bitcoin.conf" <<EOF
# Generated by the bitcoin-bip110 StartOS package.
${CHAIN_OPTION}=1
server=1
daemon=0
printtoconsole=1

# Outbound peer connections remain enabled for public test networks. StartOS
# does not expose a P2P interface for inbound connections.
networkactive=1
listen=0
discover=0
upnp=0
natpmp=0
${PEER_CONFIG}

# These credentials are shared with the companion DATUM package. RPC is
# reachable only through the StartOS service bridge.
rpcallowip=0.0.0.0/0
rpcuser=datum
rpcpassword=bip110-regtest-lab

# The public testnet4 fork requires Totoro; dummy mode retains BIP110-LAB so
# existing private chains remain compatible.
blake2b_headline=${HEADLINE}
${MODE_CONFIG}

disablewallet=1
txindex=0

# Bitcoin requires network-specific RPC bind settings to live in the selected
# network section. The RPC port is exposed only through StartOS.
[${NETWORK_SECTION}]
rpcbind=0.0.0.0
rpcport=18443
EOF

bootstrap_regtest() {
    while ! bitcoin-cli -datadir="$DATA_DIR" getblockcount >/dev/null 2>&1; do
        sleep 1
    done

    current_height="$(bitcoin-cli -datadir="$DATA_DIR" getblockcount)"
    if [ "$current_height" -lt "$BOOTSTRAP_HEIGHT" ]; then
        remaining=$((BOOTSTRAP_HEIGHT - current_height))
        echo "Bootstrapping ${remaining} real regtest block(s); BLAKE2b activates at height 20"
        bitcoin-cli -datadir="$DATA_DIR" generatetoaddress "$remaining" "$MINING_ADDRESS" >/dev/null
    fi

    current_height="$(bitcoin-cli -datadir="$DATA_DIR" getblockcount)"
    echo "BIP110 regtest ready at height ${current_height}"
}

if [ "$BOOTSTRAP_DUMMY" -eq 1 ]; then
    bootstrap_regtest &
fi

echo "Starting Bitcoin Knots in ${MODE} mode with datadir ${DATA_DIR}"
exec bitcoind -datadir="$DATA_DIR"
