#!/bin/sh
set -eu

DATA_DIR=/data
BOOTSTRAP_HEIGHT=19
MINING_ADDRESS=mipcBbFg9gMiCh81Kj8tqqdgoZub1ZJRfn

mkdir -p "$DATA_DIR"
umask 077

cat > "$DATA_DIR/bitcoin.conf" <<'EOF'
# Generated by the bitcoin-bip110 StartOS package. This service is a
# disposable, isolated regtest lab and must not be used as a mainnet node.
regtest=1
server=1
daemon=0
printtoconsole=1

# No peers means no mainnet/testnet IBD and no external chain state.
listen=0
dnsseed=0
discover=0
upnp=0
natpmp=0

# These credentials protect only valueless regtest state and are shared with
# the companion DATUM package.
rpcallowip=0.0.0.0/0
rpcuser=datum
rpcpassword=bip110-regtest-lab

# Height 20 is deliberately left for the external BLAKE2b miner.
testactivationheight=blake2b@20
blake2b_headline=BIP110-LAB

disablewallet=1
txindex=0

# Bitcoin requires network-specific RPC bind settings to live in the selected
# network section. The RPC port is exposed only through StartOS.
[regtest]
rpcbind=0.0.0.0
rpcport=18443
EOF

bootstrap_regtest() {
    while ! bitcoin-cli -datadir="$DATA_DIR" getblockcount >/dev/null 2>&1; do
        sleep 1
    done

    current_height="$(bitcoin-cli -datadir="$DATA_DIR" getblockcount)"
    if [ "$current_height" -lt "$BOOTSTRAP_HEIGHT" ]; then
        remaining=$((BOOTSTRAP_HEIGHT - current_height))
        echo "Bootstrapping ${remaining} real regtest block(s); BLAKE2b activates at height 20"
        bitcoin-cli -datadir="$DATA_DIR" generatetoaddress "$remaining" "$MINING_ADDRESS" >/dev/null
    fi

    current_height="$(bitcoin-cli -datadir="$DATA_DIR" getblockcount)"
    echo "BIP110 regtest ready at height ${current_height}"
}

bootstrap_regtest &
exec bitcoind -datadir="$DATA_DIR"
